=== WolfAppStudio/JNGLBK-data/data/schemas/item.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Learning Items",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "name",
      "media",
      "meta",
      "tags",
      "accessibility",
      "slug"
    ],
    "properties": {
      "id": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "integer"
          }
        ]
      },
      "slug": {
        "type": "string"
      },
      "name": {
        "type": "object",
        "required": [
          "en",
          "hi",
          "gu"
        ],
        "properties": {
          "en": {
            "type": "string"
          },
          "hi": {
            "type": "string"
          },
          "gu": {
            "type": "string"
          }
        }
      },
      "media": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string"
          }
        }
      },
      "meta": {
        "type": "object",
        "properties": {
          "category": {
            "type": "string"
          },
          "order": {
            "type": "integer"
          }
        }
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "accessibility": {
        "type": "object",
        "properties": {
          "altText": {
            "type": "object",
            "properties": {
              "en": {
                "type": "string"
              },
              "hi": {
                "type": "string"
              },
              "gu": {
                "type": "string"
              }
            },
            "required": [
              "en",
              "hi",
              "gu"
            ]
          }
        }
      }
    }
  }
}

=== WolfAppStudio/JNGLBK-data/data/occupations.json
[
  {
    "id": 800,
    "name": {
      "en": "Teacher",
      "hi": "शिक्षक",
      "gu": "શિક્ષક"
    },
    "media": {
      "image": "icons/occupations/occupations-teacher.png"
    },
    "meta": {
      "category": "occupations",
      "order": 1
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Teacher",
        "hi": "शिक्षक",
        "gu": "શિક્ષક"
      }
    },
    "slug": "teacher"
  },
  {
    "id": 801,
    "name": {
      "en": "Astronaut",
      "hi": "अंतरिक्ष यात्री",
      "gu": "અંતરિક્ષ યાત્રી"
    },
    "media": {
      "image": "icons/occupations/occupations-astronaut.png"
    },
    "meta": {
      "category": "occupations",
      "order": 2
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Astronaut",
        "hi": "अंतरिक्ष यात्री",
        "gu": "અંતરિક્ષ યાત્રી"
      }
    },
    "slug": "astronaut"
  },
  {
    "id": 802,
    "name": {
      "en": "Barber",
      "hi": "नाई",
      "gu": "નાઈ"
    },
    "media": {
      "image": "icons/occupations/occupations-barber.png"
    },
    "meta": {
      "category": "occupations",
      "order": 3
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Barber",
        "hi": "नाई",
        "gu": "નાઈ"
      }
    },
    "slug": "barber"
  },
  {
    "id": 803,
    "name": {
      "en": "Carpenter",
      "hi": "बढ़ई",
      "gu": "કાર્પેન્ટર"
    },
    "media": {
      "image": "icons/occupations/occupations-carpenter.png"
    },
    "meta": {
      "category": "occupations",
      "order": 4
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Carpenter",
        "hi": "बढ़ई",
        "gu": "કાર્પેન્ટર"
      }
    },
    "slug": "carpenter"
  },
  {
    "id": 804,
    "name": {
      "en": "Chef",
      "hi": "रसोइया",
      "gu": "શેફ"
    },
    "media": {
      "image": "icons/occupations/occupations-chef.png"
    },
    "meta": {
      "category": "occupations",
      "order": 5
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Chef",
        "hi": "रसोइया",
        "gu": "શેફ"
      }
    },
    "slug": "chef"
  },
  {
    "id": 805,
    "name": {
      "en": "Dentist",
      "hi": "दंत चिकित्सक",
      "gu": "દંતચિકિત્સક"
    },
    "media": {
      "image": "icons/occupations/occupations-dentist.png"
    },
    "meta": {
      "category": "occupations",
      "order": 6
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Dentist",
        "hi": "दंत चिकित्सक",
        "gu": "દંતચિકિત્સક"
      }
    },
    "slug": "dentist"
  },
  {
    "id": 806,
    "name": {
      "en": "Doctor",
      "hi": "डॉक्टर",
      "gu": "ડોક્ટર"
    },
    "media": {
      "image": "icons/occupations/occupations-doctor.png"
    },
    "meta": {
      "category": "occupations",
      "order": 7
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Doctor",
        "hi": "डॉक्टर",
        "gu": "ડોક્ટર"
      }
    },
    "slug": "doctor"
  },
  {
    "id": 807,
    "name": {
      "en": "Electrician",
      "hi": "बिजली मिस्त्री",
      "gu": "વિજળી મિસ્ત્રી"
    },
    "media": {
      "image": "icons/occupations/occupations-electrician.png"
    },
    "meta": {
      "category": "occupations",
      "order": 8
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Electrician",
        "hi": "बिजली मिस्त्री",
        "gu": "વિજળી મિસ્ત્રી"
      }
    },
    "slug": "electrician"
  },
  {
    "id": 808,
    "name": {
      "en": "Engineer",
      "hi": "अभियंता",
      "gu": "ઇજિનિયર"
    },
    "media": {
      "image": "icons/occupations/occupations-engineer.png"
    },
    "meta": {
      "category": "occupations",
      "order": 9
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Engineer",
        "hi": "अभियंता",
        "gu": "ઇજિનિયર"
      }
    },
    "slug": "engineer"
  },
  {
    "id": 809,
    "name": {
      "en": "Farmer",
      "hi": "किसान",
      "gu": "કૃષક"
    },
    "media": {
      "image": "icons/occupations/occupations-farmer.png"
    },
    "meta": {
      "category": "occupations",
      "order": 10
    },
    "tags": [
      "occupation",
      "profession",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Farmer",
        "hi": "किसान",
        "gu": "કૃષક"
      }
    },
    "slug": "farmer"
  }
]

=== WolfAppStudio/JNGLBK-data/data/colors.json
[
  {
    "id": 200,
    "name": {
      "en": "Red",
      "hi": "लाल",
      "gu": "લાલ"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 1
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Red color",
        "hi": "लाल रंग",
        "gu": "લાલ રંગ"
      }
    },
    "slug": "red"
  },
  {
    "id": 201,
    "name": {
      "en": "Blue",
      "hi": "नीला",
      "gu": "વાદળી"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 2
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Blue color",
        "hi": "नीला रंग",
        "gu": "વાદળી રંગ"
      }
    },
    "slug": "blue"
  },
  {
    "id": 202,
    "name": {
      "en": "Yellow",
      "hi": "पीला",
      "gu": "પીળો"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 3
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Yellow color",
        "hi": "पीला रंग",
        "gu": "પીળો રંગ"
      }
    },
    "slug": "yellow"
  },
  {
    "id": 203,
    "name": {
      "en": "Green",
      "hi": "हरा",
      "gu": "લીલું"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 4
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Green color",
        "hi": "हरा रंग",
        "gu": "લીલું રંગ"
      }
    },
    "slug": "green"
  },
  {
    "id": 204,
    "name": {
      "en": "Orange",
      "hi": "संतरी",
      "gu": "નારંગી"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 5
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Orange color",
        "hi": "संतरी रंग",
        "gu": "નારંગી રંગ"
      }
    },
    "slug": "orange"
  },
  {
    "id": 205,
    "name": {
      "en": "Purple",
      "hi": "बैंगनी",
      "gu": "જાંબલી"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 6
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Purple color",
        "hi": "बैंगनी रंग",
        "gu": "જાંબલી રંગ"
      }
    },
    "slug": "purple"
  },
  {
    "id": 206,
    "name": {
      "en": "Pink",
      "hi": "गुलाबी",
      "gu": "ગુલાબી"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 7
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Pink color",
        "hi": "गुलाबी रंग",
        "gu": "ગુલાબી રંગ"
      }
    },
    "slug": "pink"
  },
  {
    "id": 207,
    "name": {
      "en": "Brown",
      "hi": "भूरा",
      "gu": "ભુરો"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 8
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Brown color",
        "hi": "भूरा रंग",
        "gu": "ભુરો રંગ"
      }
    },
    "slug": "brown"
  },
  {
    "id": 208,
    "name": {
      "en": "Black",
      "hi": "काला",
      "gu": "કાળો"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 9
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Black color",
        "hi": "काला रंग",
        "gu": "કાળો રંગ"
      }
    },
    "slug": "black"
  },
  {
    "id": 209,
    "name": {
      "en": "White",
      "hi": "सफेद",
      "gu": "સફેદ"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 10
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "White color",
        "hi": "सफेद रंग",
        "gu": "સફેદ રંગ"
      }
    },
    "slug": "white"
  },
  {
    "id": 210,
    "name": {
      "en": "Gray",
      "hi": "धूसर",
      "gu": "ઢૂસરો"
    },
    "media": {
      "image": "icons/categories/colors.png"
    },
    "meta": {
      "category": "colors",
      "order": 11
    },
    "tags": [
      "color",
      "learning",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Gray color",
        "hi": "धूसर रंग",
        "gu": "ઢૂસરો રંગ"
      }
    },
    "slug": "gray"
  }
]

=== WolfAppStudio/JNGLBK-data/data/birds.json
[
  {
    "id": 600,
    "name": {
      "en": "Woodpecker",
      "hi": "कठफोड़वा",
      "gu": "કઠફોડક"
    },
    "media": {
      "image": "icons/birds/birds-woodpeacker.png"
    },
    "meta": {
      "category": "birds",
      "order": 1
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Woodpecker",
        "hi": "कठफोड़वा",
        "gu": "કઠફોડક"
      }
    },
    "slug": "woodpecker"
  },
  {
    "id": 601,
    "name": {
      "en": "Crow",
      "hi": "कौआ",
      "gu": "કાગડો"
    },
    "media": {
      "image": "icons/birds/birds-crow.png"
    },
    "meta": {
      "category": "birds",
      "order": 2
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Crow",
        "hi": "कौआ",
        "gu": "કાગડો"
      }
    },
    "slug": "crow"
  },
  {
    "id": 602,
    "name": {
      "en": "Duck",
      "hi": "बतख",
      "gu": "હંસ"
    },
    "media": {
      "image": "icons/birds/birds-duck.png"
    },
    "meta": {
      "category": "birds",
      "order": 3
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Duck",
        "hi": "बतख",
        "gu": "હંસ"
      }
    },
    "slug": "duck"
  },
  {
    "id": 603,
    "name": {
      "en": "Eagle",
      "hi": "गरुड़",
      "gu": "ગરુડ"
    },
    "media": {
      "image": "icons/birds/birds-eagle.png"
    },
    "meta": {
      "category": "birds",
      "order": 4
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Eagle",
        "hi": "गरुड़",
        "gu": "ગરુડ"
      }
    },
    "slug": "eagle"
  },
  {
    "id": 604,
    "name": {
      "en": "Falcon",
      "hi": "बाज़",
      "gu": "ગિર્દિયાલ"
    },
    "media": {
      "image": "icons/birds/birds-falcon.png"
    },
    "meta": {
      "category": "birds",
      "order": 5
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Falcon",
        "hi": "बाज़",
        "gu": "ગિર્દિયાલ"
      }
    },
    "slug": "falcon"
  },
  {
    "id": 605,
    "name": {
      "en": "Flamingo",
      "hi": "फ्लेमिंगो",
      "gu": "ફ્લેમિંગો"
    },
    "media": {
      "image": "icons/birds/birds-flamingo.png"
    },
    "meta": {
      "category": "birds",
      "order": 6
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Flamingo",
        "hi": "फ्लेमिंगो",
        "gu": "ફ્લેમિંગો"
      }
    },
    "slug": "flamingo"
  },
  {
    "id": 606,
    "name": {
      "en": "Hen",
      "hi": "मुर्गी",
      "gu": "કુકડી"
    },
    "media": {
      "image": "icons/birds/birds-hen.png"
    },
    "meta": {
      "category": "birds",
      "order": 7
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Hen",
        "hi": "मुर्गी",
        "gu": "કુકડી"
      }
    },
    "slug": "hen"
  },
  {
    "id": 607,
    "name": {
      "en": "Heron",
      "hi": "बगुला",
      "gu": "બગુલા"
    },
    "media": {
      "image": "icons/birds/birds-heron.png"
    },
    "meta": {
      "category": "birds",
      "order": 8
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Heron",
        "hi": "बगुला",
        "gu": "બગુલા"
      }
    },
    "slug": "heron"
  },
  {
    "id": 608,
    "name": {
      "en": "Honey Bee",
      "hi": "मधुमक्खी",
      "gu": "મધુમાખી"
    },
    "media": {
      "image": "icons/birds/birds-honey-bee.png"
    },
    "meta": {
      "category": "birds",
      "order": 9
    },
    "tags": [
      "insect",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Honey Bee",
        "hi": "मधुमक्खी",
        "gu": "મધુમાખી"
      }
    },
    "slug": "honey-bee"
  },
  {
    "id": 609,
    "name": {
      "en": "Owl",
      "hi": "उल्लू",
      "gu": "ઘુવડ"
    },
    "media": {
      "image": "icons/birds/birds-owl.png"
    },
    "meta": {
      "category": "birds",
      "order": 10
    },
    "tags": [
      "bird",
      "sound",
      "kids"
    ],
    "accessibility": {
      "altText": {
        "en": "Owl",
        "hi": "उल्लू",
        "gu": "ઘુવડ"
      }
    },
    "slug": "owl"
  }
]
